### ISSUE TITLE
Tamanho do AMX

### ISSUE THREAD

**Issue by devbluen** [jdkDollaR/Player-Selector#1]
```pawn
#define     CLICK_OBJECT_MODEL      (18963)
```

Eu tenho uma sugestão para esse define. No samp quando definimos um define com um valor muito alto, acontece um bug que o tamanho do .amx fica extremamente alto, como o define não está sendo utilizado para nenhum enumerador, limitador ou algo relacionado, sugeria a alteração para:

```pawn
static const  CLICK_OBJECT_MODEL  = 18963
```

O resultado acaba reduzindo o tamanho do .amx

**Comment by jdkDollaR** [comment]
Obrigado pela observação! Confesso que não sabia sobre esse impacto no tamanho do `.amx `ao usar `#define` com valores altos, e isso é algo novo para mim. Inicialmente, optei por usar `#define` por ser uma prática comum, mas faz total sentido utilizar `static const` neste caso, já que não há dependência de pré-processamento ou necessidade de replicação do valor.

Vou implementar essa alteração, garantindo uma melhor otimização e eficiência do script. Agradeço muito pela sugestão! Caso tenha mais ideias ou encontre outros pontos para melhoria, fique à vontade para compartilhar. 🤍
